name: update-release-notes

on:
  workflow_dispatch:
    inputs:
      project_version:
        type: string
        description: Version of the project to update release notes for
        required: true        
  workflow_call:
    inputs:
      project_version:
        type: string
        description: Version of the project to update release notes for
        required: true

jobs:
  release-notes:
    runs-on: thevickypedia-lite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Release Notes
        uses: thevickypedia/update-release-notes@v2
        with:
          git_token: ${{ secrets.GIT_TOKEN }}
          commit_message: "Update release notes for ${{ inputs.project_version }}"
          filename: release_notes.rst
